# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jetty-util}
  s.version = "6.1.22"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["pending/unknown"]
  s.date = %q{2009-11-22}
  s.description = %q{Utility classes for Jetty}
  s.email = %q{autobuild@javagems.org}
  s.homepage = %q{http://www.javagems.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A JavaGem version of Jetty Utilities - packaged by JavaGems (http://www.javagems.org) - original by Mort Bay Consulting (http://www.mortbay.com)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<junit>, ["~> 3.8.2"])
    else
      s.add_dependency(%q<junit>, ["~> 3.8.2"])
    end
  else
    s.add_dependency(%q<junit>, ["~> 3.8.2"])
  end
end

